### PR TITLE
Add ABCD to the list of adopters

### PR DESCRIPTION
**Pull request by mauromorales**
@j-landru let me know if all this information is ok or if you'd rather have something changed. Thanks for sharing about abcd!

### CODE REVIEW

**Comment by j-landru** [comment]
Maybe add "system and network labs" context in the description

"Polimorphic OS used for labs in education (system and network labs)" or

"Polimorphic OS used for system and network labs in education"

**Review by mauromorales — COMMENTED** [review]
Improve description (ignore, I'm still learning codespaces LOL)

**Comment by j-landru** [comment]
oupss, orthographic typo

 polymorphic written with a "y" not "i" 

 s/polimorphic/polymorphic/g

**Comment by mauromorales** [comment]
Good catch, fixed

**Pull request merged**
